apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"detector-backend-service","namespace":"default"},"spec":{"ports":[{"port":5149,"targetPort":5149}],"selector":{"app":"detector-backend"},"type":"ClusterIP"}}
  name: detector-backend-service
  namespace: default
spec:
  clusterIP: 10.43.3.38
  clusterIPs:
  - 10.43.3.38
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5149
    protocol: TCP
    targetPort: 5149
  selector:
    app: detector-backend
  sessionAffinity: None
  type: ClusterIP
