apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"detector-frontend-service","namespace":"default"},"spec":{"ports":[{"nodePort":30080,"port":80,"targetPort":3000}],"selector":{"app":"detector-frontend"},"type":"NodePort"}}
  name: detector-frontend-service
  namespace: default
spec:
  clusterIP: 10.43.190.29
  clusterIPs:
  - 10.43.190.29
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: detector-frontend
  sessionAffinity: None
  type: NodePort

